# Generated by Django 4.1.3 on 2022-11-07 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grammar', '0003_alter_client_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='no',
            field=models.FloatField(default=0),
        ),
    ]
